language: python
python:
  - 3.5
notifications: # set notification options
  slack:
    rooms:
      - ucsc-cgl:Edwfgt7MJEVZV9Lib3igueTF
    on_success: change
    on_failure: always
  email: false

install:
- sudo apt-get update
# We do this conditionally because it saves us some downloading if the
# version is the same.
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a
#- conda env create -f requirements35.yml
- pip install coverage
- pip install pytest
- python setup.py install
- cd basetensor

script:
- coverage run --source basetensor -m pytest
# - coverage run --source nanotensor -a nanotensor/tests/data_preparation_test.py
# - bash <(curl -s https://codecov.io/bash) -cF python
# after_script: # here's a build step block
# - echo "We can put normal shell commands here"
# - echo "more shell commands here"

after_success:
  - codecov -t c9b8fb3a-ca4b-45ad-947b-b790f8625d71

