language: python
python:
  - 3.5
notifications: # set notification options
  slack:
    rooms:
      - ucsc-cgl:Edwfgt7MJEVZV9Lib3igueTF
    on_success: change
    on_failure: always
  email: false

install:
- sudo apt-get update
- pip install coverage
- pip install pytest
- pip install codecov
- python setup.py install
- cd basetensor

script:
- coverage run --source basetensor -m pytest

after_success:
  - codecov -t c9b8fb3a-ca4b-45ad-947b-b790f8625d71

